In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('../DATA/split_classes.csv', index_col=False)
x = data.drop(['diabets', 'pre_diabets', 'non_diabets'], axis=1)
diabets = data['diabets']
pre_diabets = data['pre_diabets']
non_diabets = data['non_diabets']

In [3]:
print('diabets',
      pd.value_counts(diabets),
      '\npre_diabets',
      pd.value_counts(pre_diabets),
      '\nnon_diabets',
      pd.value_counts(non_diabets),
      sep='\n')

diabets
0.0    249049
1.0      4631
Name: diabets, dtype: int64

pre_diabets
0.0    218334
1.0     35346
Name: pre_diabets, dtype: int64

non_diabets
1.0    213703
0.0     39977
Name: non_diabets, dtype: int64

In [4]:
diabets_true_index = np.where(diabets == 1)[0]
diabets_false_index = np.where(diabets == 0)[0]
np.random.shuffle(diabets_false_index)
pre_diabets_true_index = np.where(pre_diabets == 1)[0]
pre_diabets_false_index = np.where(pre_diabets == 0)[0]
np.random.shuffle(pre_diabets_false_index)
non_diabets_true_index = np.where(non_diabets == 1)[0]
non_diabets_false_index = np.where(non_diabets == 0)[0]
np.random.shuffle(non_diabets_false_index)

In [5]:
diabets_data = data.drop(['pre_diabets', 'non_diabets'], axis=1).iloc[diabets_true_index]
diabets_data = pd.concat([diabets_data, 
                          data.drop(['pre_diabets', 
                                     'non_diabets'], 
                                    axis=1).iloc[diabets_false_index[0:pd.value_counts(diabets).min()]]],
                          axis=0)
diabets_data

,HighBP,HighChol,CholCheck,BMI,HvyAlcoholConsump,NoDocbcCost,GenHlth,MentHlth,Age,Income,diabets
64,1.0,1.0,1.0,0.174419,0.0,1.0,0.75,1.0,0.750000,0.285714,1.0
81,1.0,1.0,1.0,0.244186,0.0,0.0,0.50,0.1,0.500000,0.857143,1.0
193,1.0,1.0,1.0,0.255814,0.0,0.0,0.25,0.0,0.500000,1.000000,1.0
236,1.0,1.0,1.0,0.244186,0.0,0.0,1.00,1.0,0.916667,0.714286,1.0
275,1.0,1.0,1.0,0.232558,0.0,0.0,1.00,0.0,0.583333,0.857143,1.0
...,...,...,...,...,...,...,...,...,...,...,...
214050,1.0,0.0,1.0,0.244186,0.0,1.0,0.50,0.2,0.500000,0.857143,0.0
71591,0.0,0.0,1.0,0.127907,0.0,0.0,0.00,0.0,0.250000,1.000000,0.0
118917,0.0,1.0,1.0,0.174419,0.0,0.0,0.50,0.0,0.833333,1.000000,0.0
125620,1.0,1.0,1.0,0.162791,0.0,0.0,0.50,0.0,1.000000,0.714286,0.0
224636,1.0,1.0,1.0,0.186047,0.0,0.0,0.25,0.0,0.666667,0.142857,0.0

In [6]:
diabets_data.sample(frac=1).reset_index(drop=True).to_csv('../DATA/diabets_classes.csv', index=False)

In [7]:
pre_diabets_data = data.drop(['diabets', 'non_diabets'],
                         axis=1).iloc[pre_diabets_true_index]
pre_diabets_data = pd.concat([pre_diabets_data,
                          data.drop(['diabets',
                                     'non_diabets'],
                                    axis=1).iloc[pre_diabets_false_index[0:pd.value_counts(pre_diabets).min()]]],
                         axis=0)
pre_diabets_data

,HighBP,HighChol,CholCheck,BMI,HvyAlcoholConsump,NoDocbcCost,GenHlth,MentHlth,Age,Income,pre_diabets
8,1.0,1.0,1.0,0.209302,0.0,0.0,1.00,1.0,0.666667,0.000000,1.0
10,0.0,0.0,1.0,0.151163,0.0,0.0,0.50,0.0,1.000000,1.000000,1.0
13,1.0,1.0,1.0,0.186047,0.0,0.0,0.75,0.0,0.833333,0.714286,1.0
17,0.0,0.0,1.0,0.127907,0.0,0.0,0.25,0.0,0.500000,0.714286,1.0
23,1.0,0.0,1.0,0.174419,0.0,0.0,0.00,0.0,1.000000,0.428571,1.0
...,...,...,...,...,...,...,...,...,...,...,...
222325,0.0,0.0,1.0,0.174419,0.0,0.0,0.25,0.0,0.166667,1.000000,0.0
245287,0.0,0.0,1.0,0.162791,0.0,0.0,0.25,0.0,0.166667,0.857143,0.0
26528,0.0,0.0,1.0,0.325581,0.0,0.0,0.25,1.0,0.333333,1.000000,0.0
18531,0.0,1.0,1.0,0.139535,0.0,0.0,0.00,0.0,0.583333,1.000000,0.0
103930,1.0,1.0,1.0,0.162791,0.0,0.0,0.25,0.0,0.250000,0.714286,0.0

In [8]:
pre_diabets_data.sample(frac=1).reset_index(drop=True).to_csv('../DATA/pre_diabets_classes.csv', index=False)

In [9]:
non_diabets_true_index

array([     0,      1,      2, ..., 253675, 253677, 253678], dtype=int64)

In [10]:
non_diabets_data = data.drop(['diabets', 'pre_diabets'],
                             axis=1).iloc[non_diabets_true_index]
non_diabets_data = pd.concat([non_diabets_data,
                              data.drop(['diabets',
                                         'pre_diabets'],
                                        axis=1).iloc[non_diabets_false_index[0:pd.value_counts(non_diabets).min()]]],
                             axis=0)
non_diabets_data

,HighBP,HighChol,CholCheck,BMI,HvyAlcoholConsump,NoDocbcCost,GenHlth,MentHlth,Age,Income,non_diabets
0,1.0,1.0,1.0,0.325581,0.0,0.0,1.00,0.6,0.666667,0.285714,1.0
1,0.0,0.0,0.0,0.151163,0.0,1.0,0.50,0.0,0.500000,0.000000,1.0
2,1.0,1.0,1.0,0.186047,0.0,1.0,1.00,1.0,0.666667,1.000000,1.0
3,1.0,0.0,1.0,0.174419,0.0,0.0,0.25,0.0,0.833333,0.714286,1.0
4,1.0,1.0,1.0,0.139535,0.0,0.0,0.25,0.1,0.833333,0.428571,1.0
...,...,...,...,...,...,...,...,...,...,...,...
112722,1.0,1.0,1.0,0.302326,0.0,0.0,0.75,0.0,0.833333,0.714286,0.0
174929,1.0,0.0,1.0,0.209302,0.0,0.0,0.50,0.0,0.916667,0.285714,0.0
57909,1.0,1.0,1.0,0.139535,0.0,0.0,0.75,0.0,1.000000,0.142857,0.0
231359,1.0,1.0,1.0,0.197674,0.0,0.0,0.50,0.0,0.666667,1.000000,0.0
38569,1.0,0.0,1.0,0.255814,0.0,0.0,0.50,0.0,0.250000,0.714286,0.0

In [11]:
non_diabets_data.sample(frac=1).reset_index(drop=True).to_csv('../DATA/non_diabets_classes.csv', index=False)

# All

In [28]:
diabets_all_data = data.drop(['pre_diabets', 'non_diabets'], axis=1).iloc[diabets_true_index]
diabets_all_data.rename(columns={'diabets': 'diabets'})
diabets_all_data['diabets'] = diabets_all_data['diabets'] * 2
pre_diabets_all_data = data.drop(['diabets', 'non_diabets'], axis=1).iloc[pre_diabets_true_index]
pre_diabets_all_data = pre_diabets_all_data.rename(columns={'pre_diabets': 'diabets'})[0:len(diabets_true_index)]
pre_diabets_all_data['diabets'] = pre_diabets_all_data['diabets'] * 1
non_diabets_all_data = data.drop(['pre_diabets', 'diabets'], axis=1).iloc[non_diabets_true_index]
non_diabets_all_data = non_diabets_all_data.rename(columns={'non_diabets': 'diabets'})[0:len(diabets_true_index)]
non_diabets_all_data['diabets'] = non_diabets_all_data['diabets'] * 0
all = pd.concat([diabets_all_data, pre_diabets_all_data, non_diabets_all_data], axis=0).sample(frac=1).reset_index(drop=True)
all

,HighBP,HighChol,CholCheck,BMI,HvyAlcoholConsump,NoDocbcCost,GenHlth,MentHlth,Age,Income,diabets
0,1.0,1.0,1.0,0.197674,0.0,1.0,0.50,1.0,0.500000,1.000000,2.0
1,1.0,0.0,1.0,0.267442,0.0,0.0,0.75,0.0,1.000000,0.142857,1.0
2,1.0,1.0,1.0,0.162791,0.0,1.0,0.50,1.0,0.416667,0.142857,2.0
3,1.0,1.0,1.0,0.151163,0.0,0.0,0.50,0.0,0.750000,0.714286,0.0
4,1.0,1.0,1.0,0.209302,0.0,0.0,0.25,0.0,0.666667,0.857143,0.0
...,...,...,...,...,...,...,...,...,...,...,...
13888,1.0,1.0,1.0,0.244186,0.0,0.0,0.25,0.0,1.000000,0.571429,2.0
13889,0.0,1.0,1.0,0.174419,0.0,0.0,0.25,0.0,0.583333,1.000000,1.0
13890,1.0,0.0,1.0,0.232558,0.0,1.0,0.50,0.0,0.416667,0.857143,0.0
13891,1.0,0.0,1.0,0.186047,0.0,0.0,0.25,0.0,0.416667,1.000000,0.0
13892,1.0,1.0,1.0,0.162791,0.0,0.0,0.50,0.0,0.750000,0.714286,1.0

In [29]:
all.to_csv('../DATA/down_sampling.csv', index=False)